export const SET_HUOBI_PRICE = 'SET_HUOBI_PRiCE';
export const SET_BINANCE_PRICE = 'SET_BINANCE_PRICE';
export const SET_KRAKEN_PRICE = 'SET_KRAKEN_PRICE';
export const SET_BITFINEX_PRICE = 'SET_BITFINEX_PRICE';

export const SET_HUOBI_TRADES = 'SET_HUOBI_TRADES';
export const SET_BINANCE_TRADES = 'SET_BINANCE_TRADES';
export const SET_KRAKEN_TRADES = 'SET_KRAKEN_TRADES';
export const SET_BITFINEX_TRADES = 'SET_BITFINEX_TRADES';

export const SET_PAIR = 'SET_PAIR';

export const SET_PAIR_PRICE_LOADING = 'SET_PAIR_PRICE_LOADING';
export const SET_HUOBI_TRADES_LOADING = 'SET_HUOBI_TRADES_LOADING';
export const SET_BINANCE_TRADES_LOADING = 'SET_BINANCE_TRADES_LOADING';
export const SET_BITFINEX_TRADES_LOADING = 'SET_BITFINEX_TRADES_LOADING';
export const SET_KRAKEN_TRADES_LOADING = 'SET_KRAKEN_TRADES_LOADING';



